config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  post '/add_user', to: 'home#add_user'
  get  '/send_carrot', to: 'home#send_carrot'

  root 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # :registerable, :recoverable, :rememberable, :trackable
  devise :database_authenticatable, :validatable

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @user = User.new
  end

  def add_user
    user = User.create(email: params[:email], password: generate_password)

    if user.valid?
      WelcomeMailer.invite(user.email).deliver_now
      flash[:notice] = 'user added'
    else
      flash[:alert] = user.errors.full_messages.join(', ')
    end

    redirect_to root_path
  end

  def send_carrot
    user_1, user_2 = pull_two_users
    deliver_carrot_email(user_1, user_2)

    redirect_to root_path, notice: 'carrot sent'
  end

  private

  def deliver_carrot_email(email_1, email_2)
    ConnectionMailer.initiate(email_1, email_2).deliver_now
  end

  def generate_password
    Devise.friendly_token.first(8)
  end

  def pull_two_users
    User.order(:email).limit(2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
.section
  = form_tag add_user_path do
    .animated.rotateInUpRight
      = email_field_tag 'email', nil, class: "validate", placeholder: "EMAIL"
    .animated.rotateInUpRight
      = button_tag 'request invite', type: "submit"

.section.animated.rotateInUpRight
  = link_to "send carrot", send_carrot_path, id: "send-carrot", title: "send carrot"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Carrot
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      p.notice= notice
      p.alert= alert

      h1.animated.rotateInDownLeft Carrot

      == yield